name: example
description: "Example app to test integration with blendberry_flutter_sdk"
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

  shared_preferences: ^2.0.17

  blendberry_flutter_sdk:
    path: ../

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true